CREATE TABLE [audit].[Address] (
    [Id]                    INT           IDENTITY (1, 1) NOT NULL,
    [deletedEntityId]       INT           NULL,
    [insertedEntityId]      INT           NULL,
    [deletedContactTypeId]  INT           NULL,
    [insertedContactTypeId] INT           NULL,
    [deletedIsPrimary]      BIT           NULL,
    [insertedIsPrimary]     BIT           NULL,
    [deletedAddressLine1]   VARCHAR (100) NULL,
    [insertedAddressLine1]  VARCHAR (100) NULL,
    [deletedAddressLine2]   VARCHAR (100) NULL,
    [insertedAddressLine2]  VARCHAR (100) NULL,
    [deletedCity]           VARCHAR (50)  NULL,
    [insertedCity]          VARCHAR (50)  NULL,
    [deletedState]          VARCHAR (10)  NULL,
    [insertedState]         VARCHAR (10)  NULL,
    [deletedZip]            VARCHAR (10)  NULL,
    [insertedZip]           VARCHAR (10)  NULL,
    [deletedCounty]         VARCHAR (50)  NULL,
    [insertedCounty]        VARCHAR (50)  NULL,
    [deletedCountry]        VARCHAR (50)  NULL,
    [insertedCountry]       VARCHAR (50)  NULL,
    [deletedStateId]        INT           NULL,
    [insertedStateId]       INT           NULL,
    [action]                NVARCHAR (10) NULL,
    [ActionDate]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

