CREATE TABLE [audit].[Office] (
    [Id]                       INT            IDENTITY (1, 1) NOT NULL,
    [deletedEntityId]          INT            NULL,
    [deletedParentEntityId]    INT            NULL,
    [deletedUserName]          VARCHAR (40)   NULL,
    [deletedName]              VARCHAR (100)  NULL,
    [deletedOfficeId]          VARCHAR (40)   NULL,
    [deletedOfficeStatus]      VARCHAR (30)   NULL,
    [deletedNRDSID]            BIGINT         NULL,
    [deletedURL]               VARCHAR (100)  NULL,
    [deletedPhotoLocation]     VARCHAR (1000) NULL,
    [deletedMLSID]             VARCHAR (40)   NULL,
    [deletedIDXParticipation]  BIT            NULL,
    [deletedLegacyLogonType]   VARCHAR (50)   NULL,
    [deletedBrokerEntityId]    INT            NULL,
    [insertedEntityId]         INT            NULL,
    [insertedParentEntityId]   INT            NULL,
    [insertedUserName]         VARCHAR (40)   NULL,
    [insertedName]             VARCHAR (100)  NULL,
    [insertedOfficeId]         VARCHAR (40)   NULL,
    [insertedOfficeStatus]     VARCHAR (30)   NULL,
    [insertedNRDSID]           BIGINT         NULL,
    [insertedURL]              VARCHAR (100)  NULL,
    [insertedPhotoLocation]    VARCHAR (1000) NULL,
    [insertedMLSID]            VARCHAR (40)   NULL,
    [insertedIDXParticipation] BIT            NULL,
    [insertedLegacyLogonType]  VARCHAR (50)   NULL,
    [insertedBrokerEntityId]   INT            NULL,
    [action]                   NVARCHAR (10)  NULL,
    [UpdateDateTime]           DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

