INSERT INTO dbo.AccountPermission ([Id], [Name])
VALUES
	  (1, 'Change Password On Behalf Of')
	, (2, 'Create New Case')
	, (3, 'Manage Admins On Behalf Of')
	, (4, 'Purchase Base Subscriptions On Behalf Of')
	, (5, 'Purchase Add-On Subscriptions On Behalf Of')
	, (6, 'Cancel Subscriptions')
	, (7, 'View Atlas Status')
	, (8, 'View MLS Status')
	, (9, 'View Visible In Lists')
	, (10, 'View Blocked Status')
	, (11, 'Toggle MLS Status')
	, (12, 'Toggle Visible In Lists')
	, (13, 'Toggle Blocked Status')
	, (14, 'Toggle Compliance Status')
	, (15, 'View Case History Summary On Account Summary')
	, (16, 'View Subscriber Association')
	, (17, 'View Batch Id')
	, (18, 'Grant Subscriptions')
	, (19, 'Create Fines')
	, (20, 'Waive Fines')
	, (21, 'Reduce Fines')
	, (22, 'Remove Fines')
	, (23, 'Pay Fines On Behalf Of')
	, (24, 'Create Appeals')
	, (25, 'View Appeal Fee Letter')
	, (26, 'Cancel Appeals')
	, (27, 'Disposition Appeals')
	, (28, 'Waive Appeal Fee')
	, (29, 'Use Global Search')
	, (30, 'View Restricted Receipt Info')
	, (31, 'Accept Cash Payments')
	, (32, 'Accept Check Payments')
	, (33, 'Refund Orders')
	, (34, 'Process Chargebacks And NSF')
	, (35, 'Cancel Alerts')
	, (36, 'View GL Detail Report Button')
	, (37, 'View Roles')
	, (38, 'Edit Roles')

GO