CREATE TYPE [dbo].[OrderData] AS TABLE (
    [OrderNumber]            INT           NOT NULL,
    [SoldToEntityId]         INT           NULL,
    [OrderDate]              DATETIME      NULL,
    [OrderTotal]             MONEY         NULL,
    [PaymentType]            VARCHAR (20)  NULL,
    [OrderType]              VARCHAR (50)  NULL,
    [RefundType]             VARCHAR (20)  NULL,
    [OrderStatus]            VARCHAR (50)  NULL,
    [PaymentStatus]          VARCHAR (50)  NULL,
    [CheckNumber]            VARCHAR (50)  NULL,
    [CheckName]              VARCHAR (100) NULL,
    [AuthorizationCode]      VARCHAR (6)   NULL,
    [CCNumber]               VARCHAR (8)   NULL,
    [TransactionId]          VARCHAR (255) NULL,
    [ReferenceTransactionId] VARCHAR (255) NULL,
    [ReferenceOrderNumber]   INT           NULL,
    [CCExpiration]           VARCHAR (8)   NULL,
    [CCType]                 VARCHAR (50)  NULL,
    [FailureCode]            VARCHAR (25)  NULL,
    [FailureReason]          VARCHAR (255) NULL,
    [BillingFirstName]       VARCHAR (100) NULL,
    [BillingLastName]        VARCHAR (100) NULL,
    [BillingAddress]         VARCHAR (60)  NULL,
    [BillingCity]            VARCHAR (40)  NULL,
    [BillingState]           CHAR (2)      NULL,
    [BillingZip]             VARCHAR (7)   NULL,
    [BillingPhone]           VARCHAR (10)  NULL,
    [BillingEmail]           VARCHAR (100) NULL,
    [CreatedByEntityId]      INT           NULL,
    [PurchasedForEntityId]   INT           NULL,
    [BatchId]                INT           NULL,
    PRIMARY KEY CLUSTERED ([OrderNumber] ASC));

