CREATE TABLE [dbo].[ADREOffice] (
    [LegalName]                     VARCHAR (100) NULL,
    [DBAName]                       VARCHAR (100) NULL,
    [Association]                   VARCHAR (100) NULL,
    [LicenseType]                   VARCHAR (100) NULL,
    [LicenseCategory]               VARCHAR (100) NULL,
    [LicenseNumber]                 VARCHAR (100) NOT NULL,
    [LicenseStatus]                 VARCHAR (100) NULL,
    [DesignatedBrokerLicenseNumber] VARCHAR (100) NULL,
    [Address1]                      VARCHAR (100) NULL,
    [Address2]                      VARCHAR (100) NULL,
    [City]                          VARCHAR (100) NULL,
    [State]                         VARCHAR (100) NULL,
    [Zip]                           VARCHAR (100) NULL,
    [County]                        VARCHAR (100) NULL,
    [Phone]                         VARCHAR (100) NULL,
    [Fax]                           VARCHAR (100) NULL,
    [OriginalDate]                  DATE          NULL,
    [ExpireDate]                    DATE          NULL,
    [LastModifiedDate]              DATE          NULL,
    [LoadDate]                      DATETIME2 (7) NULL,
    [LoadEndDate]                   DATETIME2 (7) NULL,
    CONSTRAINT [PK_ADREOffice_Id] PRIMARY KEY CLUSTERED ([LicenseNumber] ASC)
);

